## env
#
# 
# NODE_HOSTNAME
# WEBSERVER_FQDN
#
version: '3.8'

services:

  spark:
    image: spark:python3
    command: tail -f /etc/hosts
    #command: /opt/spark/bin/pyspark
    environment:
      N8N_PATH: /n8n
    #volumes:
    #  - n8n-config:/home/node/.n8n
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
          - node.labels.webserver == true
      labels:
      - traefik.enable=true
      - traefik.port=4040
      #- traefik.frontend.rule=Host:$WEBSERVER_FQDN;PathPrefixStrip:/spark
      - traefik.frontend.rule=Host:$WEBSERVER_FQDN
      - traefik.protocol=http
      - traefik.docker.network=web
    networks:
      - web
      - default
      

  database1:
    image: mariadb:10.3
    environment:
      - MYSQL_ROOT_PASSWORD=test1
      - MYSQL_DATABASE=test1
      - MYSQL_USER=test1
      - MYSQL_PASSWORD=test1
      - TZ=America/Sao_Paulo
    command:
      - --max-allowed-packet=64M
      - --innodb-log-file-size=256M
      - --innodb-buffer-pool-size=1G
      - --log-output=TABLE
      - --slow-query-log=1
      - --character-set-server=utf8
      - --bind-address=0.0.0.0
      - --innodb-use-native-aio=0
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.database == true
      resources:
        limits:
          cpus: '2'
          memory: 2G


  database2:
    image: mariadb:10.3
    environment:
      - MYSQL_ROOT_PASSWORD=test2
      - MYSQL_DATABASE=test2
      - MYSQL_USER=test2
      - MYSQL_PASSWORD=test2
      - TZ=America/Sao_Paulo
    command:
      - --max-allowed-packet=64M
      - --innodb-log-file-size=256M
      - --innodb-buffer-pool-size=1G
      - --log-output=TABLE
      - --slow-query-log=1
      - --character-set-server=utf8
      - --bind-address=0.0.0.0
      - --innodb-use-native-aio=0
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.database == true
      resources:
        limits:
          cpus: '2'
          memory: 2G
          
volumes:
  n8n-config:
    name: "${PROJECT_NAME}-apache-spark-config"
    driver: local

  
networks:
  web:
    external: true
    name: web